# Generated by Django 3.2.14 on 2022-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'labeled_data',
                'managed': True,
            },
        ),
    ]
